RUN_STRINGS = (
    "Now you see me, now you don't.",
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_SAITAMA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to their home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost their race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
GBAM = "<b>Beginning Of Global Bam For {user2}</b>  \n \nChat Id : <code>{chatid}</code> \nReason : <i>{reason}</i> \nGBammed By {user1}"


GBAM_REASON = (
    "sasta noob",
    "sasta waifu stealer",
    "sasta white-het hekur",
    "sasta white-het codur",
    "sasta white-het vala chintu",
    "sasta hexa hekur",
    "sasta hexa playur",
    "sasta tiktokur💃🏾",
    "sasta membor of team 7",
    "sasta selmon boi",
    "sasta fri-fire player",
    "sasta chhota bhim",
    "sasta chhapri",
    "sasta jony sin",
    "sasta chhapri nibba",
    "sasta nibba",
    "sasti ria chokroborti",
    "sasti nibbi",
    "sasta camper",
)

FLIRT_TEXT = (
    "I hope you know CPR, because you just took my breath away!",
    "So, aside from taking my breath away, what do you do for a living?",
    "I ought to complain to Spotify for you not being named this week’s hottest single.",
    "Your eyes are like the ocean; I could swim in them all day.",
    "When I look in your eyes, I see a very kind soul",
    "If you were a vegetable, you’d be a ‘cute-cumber.’",
    "Do you happen to have a Band-Aid? ‘Cause I scraped my knees falling for you.",
    "I didn’t know what I wanted in a woman until I saw you.",
    "I was wondering if you could tell me: If you’re here, who’s running Heaven?",
    "No wonder the sky is gray tonight , cause all the color is in your eyes.",
    "You’ve got everything I’ve been searching for, and believe me—I’ve been looking a long time.",
    "Do you have a map? I just got lost in your eyes.",
    "*Cough* *clear throat*\nAre you a guitar? Cuz I wanna grab your neck and listen to the noise u make while I'm playing with you\n*winks*",
    "Are you an electrician? Because you’re definitely lighting up my day/night!",
    "Are you Netflix? Cause I can look at you the whole day without getting boared",
    "I’ve heard it said that kissing is the ‘language of love.’ Would you care to have a conversation with me about it sometime?",
    "Oh you're single?\nI wonder why you're not on the Spotify hot singles list",
    "I was wondering if you’re an artist because you were so good at drawing me in.",
    "Do you ever get tired from running through my thoughts all night?",
)

ROMANCE_GIFS = [
    "CgACAgQAAxkBAAIQIWC0g6ovGy7YT-Y66XfpFVEKwTXKAAJ8AgACTu6sUN0m69FQv9tHHwQ",
    "CgACAgQAAxkBAAIQImC0g62lTsbdQtBB5fY4tX5s9vP8AAJyAgACHdY1UTlYUpF2JAABcx8E",
    "CgACAgQAAxkBAAIQI2C0g7nn-TRjwilr59dtctGb_cLlAAJ6AgACNkelUhxvFpZgDUbFHwQ",
    "CgACAgQAAxkBAAIQJGC0g8L4cYfXRxE42YOTOcTCn8d9AAIoAgACqhGMUnPCWXH2RqPwHwQ",
    "CgACAgQAAxkBAAIQJWC0g9GEFeRewmfL7Ei4ZaCdQ9p4AAIEAgAC_3xlUB5O5hIl3CbxHwQ",
    "CgACAgQAAxkBAAIQJmC0g92L9jTq89JBieJCumwYCFPwAAIiAgAC1z2UUlOhsI6CxkHXHwQ"
] 

ROMANCE_STICKERS = [
    "CAACAgQAAxkBAAIQM2C0hTjoZ6imrf90bzPD6RmGkl2ZAAJaLgAClGBOA7Ky9sn-fqeXHwQ",
    "CAACAgQAAxkBAAIQNGC0hT2OqiTvCvXzONyRU8PfXejQAAJ1LgAClGBOA5yx5Lp5F-ILHwQ",
    "CAACAgQAAxkBAAIQNWC0hT9jlDuleEyc_FOs9IBVmISYAAJ2LgAClGBOA5rDqeCOsXHNHwQ",
    "CAACAgQAAxkBAAIQNmC0hUprZQ43ncln60H8tN2Df5Z2AAKILgAClGBOA28NiCHVy1AKHwQ",
    "CAACAgQAAxkBAAIQN2C0hUu7-A7rehNrLRHCAxZVMTTnAAKHLgAClGBOA3wWNsqsCiN6HwQ"
]

ROMANCE_TEMPLATES = (
    "I knew I’d never be able to remember what {user2} wore that day. But I also knew I’d never forget the way she looked.",
    "So it’s not gonna be easy. It’s gonna be really hard. We’re gonna have to work at this every day, but I want to do that because I want you. I want all of you, forever, you and me, every day.",
    "I wish I knew how to quit you.",
    "Make me a radio and turn me up when you feel low.",
    "I can't see anything that I don't like about you."
)

UWU_GIFS = [
    "CgACAgQAAxkBAAIN4GJD65bk2RdnvbMLzqe7687ZYDNDAAIoAwACvqS0Uq90GlFhzjt4IwQ",
    "CgACAgQAAxkBAAIN4WJD65406q4a0KdLA-RHS49d6siHAAIrAwACLkS1Uo0LJImx225UIwQ",
    "CgACAgQAAxkBAAIN4mJD66dMG24D1eBUfKAfYrmQgZugAAL_AgACCJrFUknN7Zt8SjAkIwQ",
    "CgACAgQAAxkBAAIN42JD67een8P09snrzvPZFm8MMVxSAALwAgACCCa9UoKU6Rzp31FJIwQ",
    "CgACAgQAAxkBAAIN5GJD68X-1U2fU1l1HAcJZtgBCWd5AAL7AgAC1s-1UoZxIW386nZnIwQ",
    "CgACAgQAAxkBAAIN5WJD69oQoI5hDU7Lz9ky7KXgn6k5AAL6AgACdh-8UkEfmSkVJgd7IwQ",
    "CgACAgQAAxkBAAIN5mJD6-eiMllgeB3BAhL0Y-mruBZeAAILAwACrp-1Urt7B_vazoYxIwQ",
    "CgACAgQAAxkBAAIN52JD7AIwj0Ev1RMzymO-LKtNj_0JAAJnAwACbDQcUkqXsKfdzZfTIwQ"
]

UWU_STICKERS = [
    "CAACAgUAAxkBAAIQdWC0moF88wE72wmUeaOLMc342mF4AAIUAwACk6CgVWhMjd9B5B1FHwQ",
    "CAACAgUAAxkBAAIQeGC0mplxufMmOxW3UjkV92OjQFYxAAJMAwAC5ryoVZ68beJeQJcYHwQ",
    "CAACAgUAAx0CS3FrwgABA7lJYN6trj9IFjVBUefGCf3XtAHB8GUAAs8DAAKT3NFVjFwwcs1XzRYgBA"
]

OWO_GIFS = [
    "CgACAgQAAx0CTrSSlQABDm2_YkPp8HL9wzeSCe8n3gWyKZJfJkAAAkYDAAJTvLxSRqXH9mrHH7ojBA",
    "CgACAgQAAxkBAAIN1GJD6loSc-oFdNFVCabk1Lz53_s5AAL2AgACT_O9UrNCKSfX9CCqIwQ",
    "CgACAgQAAxkBAAIN1WJD6lwsQ2unUCKUYm-EiHY4CEsWAALyAgACvHu9UkC2y7NU6gqvIwQ",
    "CgACAgQAAxkBAAIN1mJD6l0mt1ndgT3wUfZbPNVI-hCsAAJLAwACXte8UiP4rSzNmu0YIwQ",
    "CgACAgQAAxkBAAIN12JD6l0E3mXpbveK_11svwoRQvD5AALXAgACzU69UvlPyUAh-Lq0IwQ"
]

OWO_STICKERS = [
    "CAACAgEAAx0CRf9PfgACElxgtJhw1QnFz6IIPzzOf4QJYI06OwAC5TIAA-cvCK5J8Qz_LoGKHwQ",
    "CAACAgUAAxkBAAIQbGC0mik81vkrndPPJ7Vif9yuCdkjAAIOAgACiMGhVWgNT2REBs36HwQ"
]

SEX_TEXT = (
    "Yamete...... yamete kudasaiii!!",
    "Sleeping alone is a waste of my sexual talent, Lets sleep together and have some fun",
    "Ahhhhh\n*cums*\n please be gentle senpai",
    "So you really wanna have some naughty stuff with me right?",
    "Yea sure I can treat you better, like anyone else",
    "You sure about that?|\nI mean am a bit shy you know",
    "Can you really handle my pussy?",
    "No Sex for you sorry to say",
    "Ok.... But be gentle please",
    "ahhh.... not there... ahhhh...",
    "Lmao, Do you even have a dick?",
    "ahhh moto moto ahhhh",
    "Shut-up small dick kid!! Go do your homework"
)
